CREATE TABLE 
	REL_PESSOA_USUARIO(
		INT_ID					INT PRIMARY KEY		NOT NULL,
		INT_PESSOA_ID    		INT					NOT NULL		REFERENCES PESSOA(INT_ID),
		INT_USUARIO_ID			INT					NOT NULL		REFERENCES USUARIO(INT_ID)
);	 		