CREATE SEQUENCE
	PESSOA_SEQUENCE
		INCREMENT 1
		MINVALUE 1
		START 1
		NO MAXVALUE;
		
ALTER TABLE ONLY
	PESSOA
		ALTER COLUMN
			INT_ID
				SET DEFAULT NEXTVAL('PESSOA_SEQUENCE'::regclass);
				
CREATE SEQUENCE
	USUARIO_SEQUENCE
		INCREMENT 1
		MINVALUE 1
		START 1
		NO MAXVALUE;
		
ALTER TABLE ONLY
	USUARIO
		ALTER COLUMN
			INT_ID
				SET DEFAULT NEXTVAL('USUARIO_SEQUENCE'::regclass);
				
CREATE SEQUENCE
	PRODUTO_SEQUENCE
		INCREMENT 1
		MINVALUE 1
		START 1
		NO MAXVALUE;
		
ALTER TABLE ONLY
	PRODUTO
		ALTER COLUMN
			INT_ID
				SET DEFAULT NEXTVAL('PRODUTO_SEQUENCE'::regclass);
				
CREATE SEQUENCE
	REL_PESSOA_USUARIO_SEQUENCE
		INCREMENT 1
		MINVALUE 1
		START 1
		NO MAXVALUE;
		
ALTER TABLE ONLY
	REL_PESSOA_USUARIO
		ALTER COLUMN
			INT_ID
				SET DEFAULT NEXTVAL('REL_PESSOA_USUARIO_SEQUENCE'::regclass);